apiVersion: helm.crossplane.io/v1beta1
kind: Release
metadata:
  name: wordpress
spec:
  forProvider:
    chart:
      name: wordpress
      repository: https://charts.bitnami.com/bitnami
      version: 15.2.5
    namespace: wordpress
  providerConfigRef:
    name: helm-provider